SELECT Distinct LAUNCH_SITE FROM SpaceXDB

SELECT * FROM SpaceXDB WHERE LAUNCH_SITE LIKE 'CCA%' LIMIT 5

SELECT SUM(PAYLOAD_MASS__KG_) FROM SpaceXDB WHERE CUSTOMER='NASA (CRS)'

SELECT AVG(PAYLOAD_MASS__KG_) FROM SpaceXDB WHERE BOOSTER_VERSION='F9 v1.1'

SELECT min(DATE) FROM SpaceXDB WHERE LANDING__OUTCOME='Success (ground pad)'

SELECT BOOSTER_VERSION FROM SpaceXDB WHERE PAYLOAD_MASS__KG_ between 4000 and 6000 AND LANDING__OUTCOME='Success (drone ship)'

SELECT COUNT(*) FROM SpaceXDB WHERE MISSION_OUTCOME LIKE '%Success%' OR MISSION_OUTCOME LIKE '%Failure%'

SELECT BOOSTER_VERSION FROM SpaceXDB WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTBL)

SELECT TO_CHAR(TO_DATE(MONTH("DATE"), 'MM'), 'MONTH') AS MONTH_NAME, LANDING__OUTCOME AS LANDING__OUTCOME, BOOSTER_VERSION AS BOOSTER_VERSION, LAUNCH_SITE AS LAUNCH_SITE FROM SpaceXDB WHERE LANDING__OUTCOME = 'Failure (drone ship)' AND "DATE" LIKE '%2015%'

SELECT "DATE", COUNT(LANDING__OUTCOME) as COUNT FROM SpaceXDB WHERE "DATE" BETWEEN '2010-06-04' and '2017-03-20' AND LANDING__OUTCOME LIKE '%Success%' GROUP BY "DATE" ORDER BY COUNT(LANDING__OUTCOME) DESC